# Generated by Django 4.2.4 on 2023-10-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_competicion', '0017_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='arbitro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_arbitro', models.CharField(choices=[('P', 'PRINCIPAL'), ('J', 'JUEZ DE LINEA'), ('C', 'CUARTO HOMBRE'), ('V', 'VAR (ÁRBITRO ASISTENTE DE VIDEO)')], max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.pais')),
            ],
            options={
                'verbose_name': 'ARBITRO',
                'verbose_name_plural': 'ARBITROS',
            },
        ),
        migrations.CreateModel(
            name='terna_arbitral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TERNA ARBITRAL',
                'verbose_name_plural': 'TERNAS ARBITRALES',
            },
        ),
        migrations.CreateModel(
            name='tipo_terna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'TIPO DE TERNA ARBITRAL',
                'verbose_name_plural': 'TIPO DE TERNAS ARBITRALES',
            },
        ),
        migrations.CreateModel(
            name='detalle_terna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_juego', models.BooleanField(default=False)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_arbitro.arbitro')),
                ('terna_arbitral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_arbitro.terna_arbitral')),
                ('tipo_terna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_arbitro.tipo_terna')),
            ],
            options={
                'verbose_name': 'DETALLE DE TERNA ARBITRAL',
                'verbose_name_plural': 'DETALLE DE TERNAS ARBITRALES',
            },
        ),
    ]
