# Generated by Django 4.2.6 on 2023-10-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0004_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_competicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.entidad')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.tipo_equipo')),
            ],
        ),
    ]
