# Generated by Django 4.2.4 on 2023-10-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0013_rename_paiscompeticion_pais_competicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competicion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
