# Generated by Django 4.2.4 on 2023-10-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0015_alter_competicion_options_alter_deporte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'verbose_name': 'PATROCINADOR', 'verbose_name_plural': 'PATROCINADORES'},
        ),
    ]
