# Generated by Django 4.2.4 on 2023-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0016_alter_patrocinador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'JORNADA',
                'verbose_name_plural': 'JORNADAS',
            },
        ),
    ]
