# Generated by Django 4.2.4 on 2023-10-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0019_detalle_grupo_competicion_competicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='bandera',
            field=models.ImageField(blank=True, default='bandera/bandera_default.png', null=True, upload_to='bandera/'),
        ),
    ]
