# Generated by Django 4.2.4 on 2023-10-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_encuentros', '0001_initial'),
        ('modulo_competicion', '0017_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CATEGORIA',
                'verbose_name_plural': 'CATEGORIAS',
            },
        ),
        migrations.CreateModel(
            name='formacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'FORMACION',
                'verbose_name_plural': 'FORMACION',
            },
        ),
        migrations.CreateModel(
            name='posicion_jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'POSICION JUGADOR',
                'verbose_name_plural': 'POSICION JUGADOR',
            },
        ),
        migrations.CreateModel(
            name='tipo_equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TIPO DE EQUIPO',
                'verbose_name_plural': 'TIPO DE EQUIPOS',
            },
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('siglas', models.CharField(max_length=3)),
                ('presidente', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_principal/')),
                ('vestimenta_principal', models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_principal/')),
                ('vestimenta_secundaria', models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_secundaria/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='equipo/portada/')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.categoria')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.deporte')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.sede')),
                ('tipo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.tipo_equipo')),
            ],
            options={
                'verbose_name': 'EQUIPO',
                'verbose_name_plural': 'EQUIPOS',
            },
        ),
    ]
