# Generated by Django 4.2.4 on 2023-10-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0002_initial'),
        ('modulo_encuentros', '0004_evento_tipo_lesion_evento_persona'),
        ('modulo_equipo', '0002_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='alineacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmada', models.BooleanField(default=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.encuentro')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.formacion')),
            ],
            options={
                'verbose_name': 'ALINEACION',
                'verbose_name_plural': 'ALINEACIONES',
            },
        ),
        migrations.CreateModel(
            name='detalle_convocatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.convocatoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_contrato.contrato')),
            ],
            options={
                'verbose_name': 'DETALLE DE CONVOCATORIA',
                'verbose_name_plural': 'DETALLES DE CONVOCATORIA',
            },
        ),
        migrations.CreateModel(
            name='detalle_alineacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dorsal', models.IntegerField()),
                ('capitan', models.BooleanField(default=False)),
                ('titular', models.BooleanField(default=False)),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.alineacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.equipo')),
                ('juagador_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_contrato.contrato')),
                ('posicion_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.detalle_convocatoria')),
            ],
        ),
    ]
