# Generated by Django 4.2.4 on 2023-11-02 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_equipo', '0005_alter_detalle_convocatoria_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
