# Generated by Django 4.2.4 on 2023-10-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('P', 'PRÉSTAMO'), ('C', 'COMPRA'), ('L', 'LIBRE'), ('R', 'RENOVACIÓN'), ('S', 'SELECCIÓN')], max_length=1)),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dorsal', models.PositiveSmallIntegerField()),
                ('posicion', models.CharField(choices=[('Portero', 'Portero'), ('Defensa: Defensa central, lateral, libre y carrilero', 'Defensa: Defensa central, lateral, libre y carrilero'), ('Centrocampista: Pivote, media punta, volante e interior', 'Centrocampista: Pivote, media punta, volante e interior'), ('Delantero: Segundo delantero, delantero centro y extremo', 'Delantero: Segundo delantero, delantero centro y extremo')], max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CONTRATO',
                'verbose_name_plural': 'CONTRATOS',
            },
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TIPO DE PERSONA',
                'verbose_name_plural': 'TIPO DE PERSONAS',
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_contrato.tipo_persona')),
            ],
            options={
                'verbose_name': 'PERSONA',
                'verbose_name_plural': 'PERSONAS',
            },
        ),
    ]
