# Generated by Django 4.2.4 on 2023-10-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_encuentros', '0004_evento_tipo_lesion_evento_persona'),
        ('modulo_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='convocatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.encuentro')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.equipo')),
            ],
            options={
                'verbose_name': 'CONVOCATORIA',
                'verbose_name_plural': 'CONVOCATORIAS',
            },
        ),
    ]
