# Generated by Django 4.2.4 on 2023-10-31 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_equipo', '0003_alineacion_detalle_convocatoria_detalle_alineacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_alineacion',
            options={'verbose_name': 'ALIENEACION EQUIPO', 'verbose_name_plural': 'ALINEACIONES DE EQUIPOS'},
        ),
    ]
