# Generated by Django 4.2.4 on 2023-10-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0003_alter_persona_foto'),
        ('modulo_equipo', '0004_alter_detalle_alineacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_convocatoria',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_contrato.persona'),
        ),
    ]
