# Generated by Django 4.2.4 on 2023-11-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_equipo', '0006_alter_convocatoria_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_convocatoria',
            name='activo',
        ),
    ]
