# Generated by Django 4.2.6 on 2023-10-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
    ]
