# Generated by Django 4.2.6 on 2023-10-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0003_pais_bandera'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('afileacion', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('ambito', models.CharField(choices=[('Fútbol', 'Fútbol')], max_length=30)),
                ('ubicado_en', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.pais')),
            ],
        ),
    ]
