# Generated by Django 4.2.6 on 2023-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0006_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='posicion_repesca',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_equipos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_equipos_clasificacion_directa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_equipos_clasificacion_fase_previa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_equipos_clasificacion_grupo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_etapas',
            field=models.IntegerField(choices=[(6, '32avos de Final '), (5, '16avos de Final'), (4, '8avos de Final'), (3, '4tos de Final '), (2, 'Semifinal'), (1, 'Final')]),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_grupos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
