# Generated by Django 4.2.4 on 2023-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0008_alter_temporada_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='deporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_etapas',
            field=models.IntegerField(choices=[(0, 'NO TIENE'), (6, '32avos de Final '), (5, '16avos de Final'), (4, '8avos de Final'), (3, '4tos de Final '), (2, 'Semifinal'), (1, 'Final')], default=0),
        ),
        migrations.AlterField(
            model_name='formato',
            name='cantidad_jornadas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
