# Generated by Django 4.2.4 on 2023-10-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0009_deporte_alter_formato_cantidad_etapas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='competicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.deporte')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.formato')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.temporada')),
                ('tipo_competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.tipo_competicion')),
            ],
        ),
    ]
