# Generated by Django 4.2.4 on 2023-10-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0010_competicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='pais_competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.competicion')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.pais')),
            ],
        ),
    ]
