# Generated by Django 4.2.4 on 2023-10-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0011_alter_competicion_nombre_pais_competicion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pais_competicion',
            new_name='PaisCompeticion',
        ),
        migrations.AddField(
            model_name='competicion',
            name='paises',
            field=models.ManyToManyField(through='modulo_competicion.PaisCompeticion', to='modulo_competicion.pais'),
        ),
    ]
