# Generated by Django 4.2.4 on 2023-10-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_competicion', '0017_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_grupo_competicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'EQUIPO QUE PERTENEN A UN COMPETICION',
                'verbose_name_plural': 'EQUIPOS QUE PERTENEN A COMPETICIONES',
            },
        ),
        migrations.CreateModel(
            name='fase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'FASE',
                'verbose_name_plural': 'FASES',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'GRUPO',
                'verbose_name_plural': 'GRUPOS',
            },
        ),
    ]
