# Generated by Django 4.2.4 on 2023-10-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_equipo', '0001_initial'),
        ('modulo_competicion', '0018_detalle_grupo_competicion_fase_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_grupo_competicion',
            name='competicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.competicion'),
        ),
        migrations.AddField(
            model_name='detalle_grupo_competicion',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_equipo.equipo'),
        ),
        migrations.AddField(
            model_name='detalle_grupo_competicion',
            name='fase',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.fase'),
        ),
        migrations.AddField(
            model_name='detalle_grupo_competicion',
            name='grupo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.grupo'),
        ),
    ]
