# Generated by Django 4.2.4 on 2023-10-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_equipo', '0001_initial'),
        ('modulo_arbitro', '0001_initial'),
        ('modulo_encuentros', '0001_initial'),
        ('modulo_competicion', '0017_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_local', to='modulo_equipo.equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_vistante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_visita', to='modulo_equipo.equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.jornada'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.sede'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='terna_arbitral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_arbitro.terna_arbitral'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_competicion.pais'),
        ),
    ]
