# Generated by Django 4.2.4 on 2023-10-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0002_initial'),
        ('modulo_encuentros', '0003_rename_competicioin_encuentro_competicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EVENTO',
                'verbose_name_plural': 'EVENTOS',
            },
        ),
        migrations.CreateModel(
            name='tipo_lesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'TIPO DE LESION',
                'verbose_name_plural': 'TIPO DE LESIONES',
            },
        ),
        migrations.CreateModel(
            name='evento_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.encuentro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.evento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_contrato.contrato')),
                ('tipo_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_encuentros.tipo_lesion')),
            ],
            options={
                'verbose_name': 'EVENTO DURANTE EL ENCEUNTRO',
                'verbose_name_plural': 'EVENTOS DURANTE LOS ENCEUNTROS',
            },
        ),
    ]
